# Generated by Django 5.1.4 on 2025-01-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
